data:
  langs:
    - de 
  test_data_root: /home/tommaso/onesec_new_multilingual/evaluation/
  train_data_root:
    - /home/tommaso/onesec_new_multilingual/data/onesec.de.data.xml
  sense_inventory: bnoffsets
  label_from_training: False
  gold_id_separator: " "
  outpath: data/models/de_onesec_new_evaluation
  mfs_file:
  test_names:
    - semeval2013-de
    - semeval2013-de-nasari
  max_sentence_token: 30
  sliding_window: 15
  max_segments_in_batch: 2000


model:
  device: cpu 
  model_name: bert-base-multilingual-cased
  learning_rate: 1e-4

training:
  num_epochs: 25
  cache_instances: True

#wandb:
#  tags:
#    - en
#    - bert-large-cased
