data:
  langs:
    - it
  test_data_root: /home/tommaso/dev/intellijWorkspace/babelnet_mapping_4.0/data/out/multilingual_wsd_v0.1.4 #/home/tommaso/Documents/data/WSD_Evaluation_Framework_2.0/Evaluation_Datasets/
  train_data_root:
    - /home/tommaso/Documents/data/onesec_new/onesec.it.data.xml
  sense_inventory: bnoffsets
  label_from_training: False
  gold_id_separator: " "
  outpath: data3/models/it_onesec_new_framework
  mfs_file: /home/tommaso/dev/intellijWorkspace/babelnet_mapping_4.0/data/out/multilingual_wsd_v0.1.5/inventory.it.sorted.withgold.txt
  test_names:
    - semeval2013-it
      #- semeval2015-it
  max_sentence_token: 30
  sliding_window: 15
  max_segments_in_batch: 2000


model:
  device: cuda 
  model_name: bert-base-multilingual-cased
  learning_rate: 1e-4

training:
  num_epochs: 25
  cache_instances: True

#wandb:
#  tags:
#    - en
#    - bert-large-cased
