data:
  langs:
    - en
    - it
    - es
    - fr
    - de
    - zh
  test_data_root: /home/tommaso/Documents/data/WSD_Evaluation_Framework_3.0/Evaluation_Datasets/
  train_data_root:
    - data2/training_data/en_training_data/semcor/semcor.data.xml
    - data2/training_data/en_training_data/princeton_tagged_glosses/semeval2013_format/princeton_examples.all.data.xml
  sense_inventory: bnoffsets
  outpath: data4/models/en_semcor_wngt_all/
  test_names:
    - senseval2
    - senseval3
    - semeval2007
    - semeval2007-coarse
    - semeval2010
    - semeval2013
    - semeval2015
    - ALL-no-semeval2007
    - semeval2010-it
    - semeval2010-zh
    - semeval2013-it
    - semeval2015-it
    - semeval2013-es
    - semeval2015-es
    - semeval2013-fr
    - semeval2013-de
  dev_name: semeval2007

  max_segments_in_batch: 1000

model:
  device: cuda
  model_name: xlm-roberta-large


  learning_rate: 1e-4

training:
  num_epochs: 25
  cache_instances: True

#wandb:
#  tags:
#    - bert-large-cased
#    - sensekey
