data:
  langs:
    - it
  test_data_root: /home/tommaso/Documents/data/WSD_Evaluation_Framework_2.0/Evaluation_Datasets/
  train_data_root:
    - data2/training_data/multilingual_training_data/onesec/it/onesec.it.test_set_lemmas.data.xml #/home/tommaso/Documents/data/WSD_Evaluation_Framework_2.0/Training_Corpora/
  sense_inventory: babelnet
  label_from: bnids_manual
  gold_id_separator: " "
  outpath: data3/models/it_onesec_manual_mapping
  mfs_file: resources/mfs/mfs_bn.it.bnids.txt
  test_names:
    - wiki_dev_it
    - wiki_test_it
    - semeval2013_it_wnfilter
    - semeval2015_it_wnfilter
  max_sentence_token: 30
  sliding_window: 15
  max_segments_in_batch: 2000
  dev_name: wiki_dev_it


model:
  device: cuda 
  model_name: bert-base-multilingual-cased
  learning_rate: 1e-4

training:
  num_epochs: 25
  cache_instances: True

#wandb:
#  tags:
#    - en
#    - bert-large-cased
