data:
  langs:
    - en
    - it
    - es
    - fr
    - de
    - zh
    - ca
    - bg
    - eu
    - gl
    - hr
    - da
    - nl
    - et
    - hu
    - ja
    - ko
    - sl
  test_data_root: /home/tommaso/Documents/data/WSD_Evaluation_Framework_3.0/new_evaluation_datasets
  train_data_root:
    en:
      - /home/tommaso/dev/PycharmProjects/WSDframework/data2/training_data/en_training_data/semcor/semcor.data.xml
      - /home/tommaso/dev/PycharmProjects/WSDframework/data2/training_data/en_training_data/wngt_michele/wngt_michele_examples/wngt_michele_examples.data.xml
      - /home/tommaso/dev/PycharmProjects/WSDframework/data2/training_data/en_training_data/wngt_michele/wngt_michele_glosses/wngt_michele_glosses.data.xml
  sense_inventory: bnoffsets
  outpath: data4/models/en_semcor_wngt_bn/
  test_names:
    en:
      - test-en
      - test-en-coarse
      - test-en-no-sem10-no-sem07
      - dev-en
    it:
      - test-it
      - dev-it
    es:
      - test-es
      - dev-es
    fr:
      - test-fr
      - dev-fr
    de:
      - test-de
      - dev-de
    zh:
      - test-zh
      - dev-zh
    gl:
      - test-gl
      - dev-gl
    hr:
      - test-hr
      - dev-hr
    da:
      - test-da
      - dev-da
    et:
      - test-et
      - dev-et
    ja:
      - test-ja
      - dev-ja
    hu:
      - test-hu
      - dev-hu
    bg:
      - test-bg
      - dev-bg
    eu:
      - test-eu
      - dev-eu
    ca:
      - test-ca
      - dev-ca
    ko:
      - test-ko
      - dev-ko
    sl:
      - test-sl
      - dev-sl
    nl:
      - test-nl
      - dev-nl
  dev_name:
    - en
    - dev-en

  max_segments_in_batch: 1000
  force_reload: True

model:
  device: cuda
  encoder_name: bert-base-multilingual-cased #xlm-roberta-large #bert-base-multilingual-cased
  wsd_model_name: batchnorm_wsd_classifier #ff_wsd_classifier #batchnorm_wsd_classifier
  layers_to_use:
    - -1
    - -2
    - -3
    - -4
  cache_instances: True
  finetune_embedder: False

training:
  num_epochs: 50
  gradient_accumulation: 1
  patience: 3
  learning_rate: 2e-5
  gradient_clipping: 1.0
  validation_metric: -loss
random_seed: 123
wandb:
  metrics_to_report:
    - f1
    - loss
    - epoch
  soft_match: True
