data:
  langs:
    - es
  test_data_root: /home/tommaso/Documents/data/WSD_Evaluation_Framework_2.0/Evaluation_Datasets/
  train_data_root:
      - data/training_data/en_training_data/onesec_original_data/onesec_testset_instances/OneSeC_ES.data.xml
  sense_inventory: bnoffsets
  label_from_training: False
  gold_id_separator: " "
  outpath: data2/models/es_onesec_original
  mfs_file: resources/mfs/mfs_bn.es.bnids.txt
  test_names:
    - wiki_dev_es
    - wiki_test_es
    - semeval2013_es_wnfilter
    - semeval2015_es_wnfilter

  max_sentence_token: 30
  sliding_window: 15
  max_segments_in_batch: 2000
  dev_name: wiki_dev_es


model:
  device: cuda 
  model_name: bert-base-multilingual-cased
  learning_rate: 1e-4

training:
  num_epochs: 25
  cache_instances: True

#wandb:
#  tags:
#    - en
#    - bert-large-cased
