data:
  langs:
    - it
  test_data_root: /home/tommaso/Documents/data/SemEval/dataset_onesec/
  #/home/tommaso/Documents/data/WSD_Evaluation_Framework_2.0/Evaluation_Datasets/
  train_data_root:
    - data2/training_data/multilingual_training_data/onesec/it/onesec.it.all.data.xml

  sense_inventory: bnoffsets 
  label_from_training: False
  gold_id_separator: " "
  outpath: data3/models/it_onesec_full
  mfs_file: resources/mfs/mfs_bn.it.bnids.txt
  test_names:
      #- wiki_dev_it
      #- wiki_test_it
    - semeval2013_it
  max_sentence_token: 30
  sliding_window: 15
  max_segments_in_batch: 2000
  dev_name: semeval2013_it 


model:
  device: cuda 
  model_name: bert-base-multilingual-cased
  learning_rate: 1e-4

training:
  num_epochs: 25
  cache_instances: True

#wandb:
#  tags:
#    - en
#    - bert-large-cased
