data:
  langs:
    - fr 
  test_data_root: /home/tommaso/WSD_Evaluation_Framework_2.0/Evaluation_Datasets/
  train_data_root:
    - data/training_data/multilingual_training_data/onesec/fr/onesec.fr.test_set_lemmas.data.xml
    - data/training_data/multilingual_training_data/babel_glosses/fr/glosses_fr.parsed.test_set_lemmas.data.xml
  sense_inventory: bnoffsets
  label_from_training: False
  gold_id_separator: " "
  outpath: data2/models/fr_o+g
  mfs_file: resources/mfs/mfs_bn.fr.bnids.txt
  test_names:
    - wiki_dev_fr
    - wiki_test_fr
    - semeval2013_fr_wnfilter
  max_sentence_token: 30
  sliding_window: 15
  max_segments_in_batch: 2000
  dev_name: wiki_dev_fr


model:
  device: cuda 
  model_name: bert-base-multilingual-cased
  learning_rate: 1e-4

training:
  num_epochs: 25
  cache_instances: True

#wandb:
#  tags:
#    - en
#    - bert-large-cased
