data:
  langs:
   - en
   - es
   - fr
   - de
   - it
  test_data_root: /home/tommaso/Documents/data/SemEval/dataset_onesec #/home/tommaso/Documents/data/WSD_Evaluation_Framework_2.0/Evaluation_Datasets/
  train_data_root:
    - data2/training_data/en_training_data/semcor+princeton_glosses/semcor+princeton_glosses_manual.data.xml

  gold_id_separator: " "
  outpath: data3/models/en_semcor_gloss_manual_zero_shot_NHS/
  label_from_training: False 
  sense_inventory: bnoffsets 
  #mfs_file: resources/mfs/mfs.zeroshot.bnid.txt
  test_names:
      #- senseval2
      #- senseval3
      #- semeval2007
      #- semeval2007_coarse
      #- semeval2010
      #- semeval2013
      #- semeval2015
      #- ALL
      #- ALL_no_semeval2007
    - semeval2013_it
    - semeval2015_it
    - semeval2013_es
    - semeval2015_es
    - semeval2013_fr
    - semeval2013_de
      #dev_name: semeval2007
  max_sentence_token: 30
  sliding_window: 15
  max_segments_in_batch: 2000

model:
  device: cuda
  model_name: bert-base-multilingual-cased
  model_path: /home/tommaso/Downloads/nhs_model/temp-output-dir-cosine_swahili/checkpoint-1110000/pytorch_model.bin
  learning_rate: 1e-4

training:
  num_epochs: 25
  cache_instances: True
