data:
  langs:
    - en
  #  lemma2synsetpath: /media/tommaso/My Book/factories/output/lemma2bnsynsets.wn_part.en.txt
  test_data_root: /home/tommaso/Documents/data/WSD_Evaluation_Framework_2.0/Evaluation_Datasets/
  train_data_root:
    - data2/training_data/en_training_data/semcor/semcor.data.xml #/home/tommaso/Documents/data/WSD_Evaluation_Framework_2.0/Training_Corpora/
  sense_inventory: wnoffsets 
  label_from_training: False
  gold_id_separator: " "
  outpath: data/models/en_semcor_wnoffsets_full_finetuning/
  #mfs_file: resources/mfs/mfs_wn.en.wnoffset.txt
  test_names:
    - senseval2
    - senseval3
    - semeval2007
    - semeval2007_coarse
    - semeval2010
    - semeval2013
    - semeval2015
    - ALL
    - ALL_no_semeval2007
  dev_name: semeval2007

  max_sentence_token: 30
  sliding_window: 15
  max_segments_in_batch: 800 

model:
  device: cuda 
  model_name: bert-large-cased
  learning_rate: 2e-5
  finetune: True

training:
  num_epochs: 25
  cache_instances: True

#wandb:
#  tags:
#    - bert-large-cased
#    - sensekey
