data:
  lazy: True
  langs:
    - fr 
  test_data_root: /home/tommaso/Documents/data/SemEval/dataset_onesec/
  train_data_root:
    - /home/tommaso/Documents/data/train-o-matic/FR/evaluation-framework-ims-training.fw20.new.data.xml
  sense_inventory: bnoffsets
  label_from_training: False
  gold_id_separator: " "
  outpath: data3/models/it_tom
  #mfs_file: resources/mfs/mfs_bn.it.bnids.txt
  test_names:
    - semeval2013_fr
  max_sentence_token: 30
  sliding_window: 15
  max_segments_in_batch: 2000
  #dev_name: wiki_dev_it


model:
  device: cuda 
  model_name: bert-base-multilingual-cased
  learning_rate: 1e-4

training:
  num_epochs: 25
  cache_instances: True

#wandb:
#  tags:
#    - en
#    - bert-large-cased
