data:
  langs:
    - de 
  test_data_root: /home/tommaso/Documents/data/WSD_Evaluation_Framework_2.0/Evaluation_Datasets/
  train_data_root:
    - /home/tommaso/Documents/data/train-o-matic/IT/evaluation-framework-ims-training.fw20.new.data.xml
  sense_inventory: bnoffsets
  label_from_training: False
  gold_id_separator: " "
  outpath: data3/models/it_tom
  mfs_file: resources/mfs/mfs_bn.it.bnids.txt
  test_names:
    - wiki_dev_it
    - wiki_test_it
    - semeval2013_it_wnfilter
    - semeval2015_it_wnfilter
  max_sentence_token: 30
  sliding_window: 15
  max_segments_in_batch: 2000
  dev_name: wiki_dev_it


model:
  device: cuda 
  model_name: bert-base-multilingual-cased
  learning_rate: 1e-4

training:
  num_epochs: 25
  cache_instances: True

#wandb:
#  tags:
#    - en
#    - bert-large-cased
